
node_types:

  ##########################################
  # Represents a master/node
  ##########################################
  cloudify.kubernetes.Master:
    derived_from: cloudify.kubernetes.Base
    properties:
      install_docker:
        default: false
      master_port:
        default: 8080
    interfaces:
      cloudify.interfaces.lifecycle:
        start: kubernetes.kube_plugin.start_master_ubuntu14.start_master

  ##########################################
  # Represents a minion/node
  ##########################################
  cloudify.kubernetes.Node:
    derived_from: cloudify.kubernetes.Base
    interfaces:
      cloudify.interfaces.lifecycle:
        start: kubernetes.kube_plugin.start_node_ubuntu14.start_node
    
  ##########################################
  # Represents a kubernetes service
  ##########################################
  cloudify.kubernetes.Microservice:
    derived_from: cloudify.kubernetes.Base
    properties:
      name:
        description: the name of the service
      image:
        description: the image to run
        default: ''
      port:
        description: the port for the service
        default: -1
      target_port:
        description: the target port to map
        default: {get_property: [SELF,port]}
     
    interfaces:
      cloudify.interfaces.lifecycle:
        start:
          implementation: kubernetes.kube_plugin.tasks.kube_run_expose
        stop:
          #no non-remote implementation yet
          implementation: kubernetes.kube_plugin.remote_tasks.kube_delete


relationships:
  cloudify.kubernetes.relationships.connected_to_master:
    derived_from: cloudify.relationships.connected_to
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        postconfigure:
          implementation: kubernetes.kube_plugin.tasks.connect_master
